version: 1
disable_existing_loggers: False
formatters:
        simple:
            format: "%(asctime)s - %(filename)s - %(lineno)s - %(levelname)s - %(message)s"
            datefmt: "%Y-%m-%d %H:%M:%S %a"
handlers:
    console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout

    info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: simple
            filename: ./log/info.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8

    error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: ./log/error.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
loggers:
    my_module:
            level: DEBUG
            handlers: [console]
            propagate: no
root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]